# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    # Sync certificates
    match(type: "appstore") 

    # Build the app
    increment_build_number(xcodeproj: "WhatThePhrase.xcodeproj")
    build_app(scheme: "WhatThePhrase")
    
    # Upload to TestFlight
    upload_to_testflight
  end

  desc "Push a new build to the App Store (Public Release)"
  lane :release do
    # Sync certificates
    match(type: "appstore")
    
    # Build the app
    increment_build_number(xcodeproj: "WhatThePhrase.xcodeproj")
    build_app(scheme: "WhatThePhrase")
    
    # Upload to App Store
    # This will use the same App-Specific Password environment variable you used for beta
    upload_to_app_store(
      skip_metadata: false,
      skip_screenshots: false,   # Uploads from ./screenshots folder
      skip_binary_upload: false,
      submit_for_review: true,    # Automatically submits for review
      automatic_release: false,    # Requires you to click "Release" manually in App Store Connect
      force: true
    )
  end
end

desc "Upload only screenshots (no build)"
lane :upload_screenshots do
  upload_to_app_store(
    skip_binary_upload: true,
    skip_metadata: true,
    skip_screenshots: false
  )
end

desc "Build for local development"
lane :develop do
  build_app(scheme: "Development")
end

lane :generate_appicon do
  appicon(
    appicon_image_file: 'WhatThePhrase/Assets/Images/AppIcon.png',
    appicon_devices: [:ipad, :iphone, :ios_marketing],
    appicon_path: "WhatThePhrase/Assets.xcassets"
  )
end

lane :generate_launch_image do
  appicon(
    appicon_image_file: "WhatThePhrase/Assets/Images/AppLaunchScreen.png",
    appicon_devices: [:iphone],
    appicon_path: "WhatThePhrase/Assets.xcassets",
    appicon_name: "LaunchImage"
  )
end
