# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  app_store_connect_api_key(
    key_id: "5YWYTPY78B",
    issuer_id: "c95787ec-9536-476a-bdd0-579e0e62897b",
    key_content: "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR1RBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdT\nTTQ5QXdFSEJIa3dkd0lCQVFRZ0ttT3BhZ0lOYlhCc0ZWS2UKVzlxcnJIaEI3NmZ5UjlpWW5YOU5p\nY01ab0NlZ0NnWUlLb1pJemowREFRZWhSQU5DQUFUWTBWUU5MdVMyWXR1SgozRDJYK2hsRGhWSkJ6\nK2wwY01zdjZGWE1xaEVLU3FCTG5jZTNMVFZGK0RKYjZFVWxZVEpLNU03ckNyODVzMXNmCm9Wc2lV\nY0V1Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0=",
    in_house: false,
    is_key_content_base64: true
  )
  
  desc "Push a new beta build to TestFlight"
  lane :beta do
    build
    pilot  
  end
end

desc "Sync certificates"
  lane :sync_certificates do
    #read-only disables match from overriding the existing certificates.
    match({readonly: true, type: "appstore"})
end

desc "Create ipa"
  lane :build do
    #update profiles
    sync_certificates
    # Increases the build number by 1
    increment_build_number
    # Creates a signed file
    gym
end

lane :generate_appicon do
  appicon(appicon_image_file: '/Users/tytalus/Documents/XCodeApps/WhatThePhrase/WhatThePhrase/Assets/Images/tytalus_Beautiful_application_icon_for_a_Catch_Phrase_app_desig_d22d65a6-d6ef-4eeb-95a3-be3bd4b362b3.png',
             appicon_devices: [:ipad, :iphone, :ios_marketing],
             appicon_path: "WhatThePhrase/Assets.xcassets")
end

lane :develop do
  build_app(scheme: "Development")
end