# A list of devices you want to take the screenshots from
devices([
  "iPhone 15 Pro Max",
  "iPhone 8 Plus"
])

languages([
  "en-US"
])

scheme("WhatThePhraseScreenShots")

clear_previous_screenshots(true)
override_status_bar(true)
erase_simulator(true)
reinstall_app(true)
